//! Tests that verify our Rust kernel produces identical hashes for
//! the types of real Init constants, compared to Lean 4.25.2's C++ kernel.
//!
//! Source of truth: /r/tmp/lean4/kernelops.txt generated by KernelOps.lean

use lean4_kernel::name::Name;
use lean4_kernel::level::Level;
use lean4_kernel::expr::{Expr, BinderInfo};

// Helper: build Type u = Sort(succ(param u))
fn type_u(u: &str) -> Expr {
    Expr::mk_sort(&Level::mk_succ(&Level::mk_param(&Name::str(u))))
}

// ============================================================================
// Constants whose types we can construct by hand and verify hash
// ============================================================================

// CONST Nat kind=induct type_hash=3931117990 (Type = Sort 1)
#[test]
fn test_nat_type() {
    let ty = Expr::mk_sort(&Level::one()); // Type = Sort 1
    assert_eq!(ty.hash(), 3931117990);
}

// CONST Nat.zero kind=ctor type_hash=421340980 (Nat)
#[test]
fn test_nat_zero_type() {
    let ty = Expr::mk_const(&Name::str("Nat"), &[]);
    assert_eq!(ty.hash(), 421340980);
}

// CONST Nat.succ kind=ctor type_hash=2546708756 (Nat → Nat)
#[test]
fn test_nat_succ_type() {
    let nat = Expr::mk_const(&Name::str("Nat"), &[]);
    let ty = Expr::mk_pi(&Name::str("n"), BinderInfo::Default, &nat, &nat);
    assert_eq!(ty.hash(), 2546708756);
    assert_eq!(ty.approx_depth(), 1);
}

// CONST Bool kind=induct type_hash=3931117990 (Type = Sort 1)
#[test]
fn test_bool_type() {
    let ty = Expr::mk_sort(&Level::one());
    assert_eq!(ty.hash(), 3931117990);
}

// CONST Bool.true kind=ctor type_hash=183048209 (Bool)
#[test]
fn test_bool_true_type() {
    let ty = Expr::mk_const(&Name::str("Bool"), &[]);
    assert_eq!(ty.hash(), 183048209);
}

// CONST True kind=induct type_hash=3944470172 (Prop = Sort 0)
#[test]
fn test_true_type() {
    let ty = Expr::mk_sort(&Level::zero());
    assert_eq!(ty.hash(), 3944470172);
}

// CONST True.intro kind=ctor type_hash=3270818714 (True)
#[test]
fn test_true_intro_type() {
    let ty = Expr::mk_const(&Name::str("True"), &[]);
    assert_eq!(ty.hash(), 3270818714);
}

// CONST False kind=induct type_hash=3944470172 (Prop = Sort 0)
#[test]
fn test_false_type() {
    let ty = Expr::mk_sort(&Level::zero());
    assert_eq!(ty.hash(), 3944470172);
}

// CONST List kind=induct type_hash=3807510281
// List.{u} : Type u → Type u = Pi("α", Sort(succ(param u)), Sort(succ(param u)))
#[test]
fn test_list_type() {
    let u = Level::mk_param(&Name::str("u"));
    let su = Level::mk_succ(&u);
    let sort_su = Expr::mk_sort(&su);
    let ty = Expr::mk_pi(&Name::str("α"), BinderInfo::Default, &sort_su, &sort_su);
    assert_eq!(ty.hash(), 3807510281);
    assert_eq!(ty.approx_depth(), 1);
    assert!(ty.has_univ_param());
}

// CONST And kind=induct type_hash=2232915537
// And : Prop → Prop → Prop = Pi("a", Sort 0, Pi("b", Sort 0, Sort 0))
#[test]
fn test_and_type() {
    let prop = Expr::mk_sort(&Level::zero());
    let inner = Expr::mk_pi(&Name::str("b"), BinderInfo::Default, &prop, &prop);
    let ty = Expr::mk_pi(&Name::str("a"), BinderInfo::Default, &prop, &inner);
    assert_eq!(ty.hash(), 2232915537);
    assert_eq!(ty.approx_depth(), 2);
}

// CONST Or kind=induct type_hash=2232915537 (same as And: Prop → Prop → Prop)
#[test]
fn test_or_type() {
    let prop = Expr::mk_sort(&Level::zero());
    let inner = Expr::mk_pi(&Name::str("b"), BinderInfo::Default, &prop, &prop);
    let ty = Expr::mk_pi(&Name::str("a"), BinderInfo::Default, &prop, &inner);
    assert_eq!(ty.hash(), 2232915537);
}

// CONST Nat.add kind=def type_hash=4163592787
// Actual type: Pi(_, MData(Nat), Pi(_, MData(Nat), Nat))
// The MData wrapper changes the hash (domains are annotated in Init)
#[test]
fn test_nat_add_type() {
    let nat = Expr::mk_const(&Name::str("Nat"), &[]);
    let md_nat = Expr::mk_mdata(&nat);  // domain is MData(Nat)
    let inner = Expr::mk_pi(&Name::str("a"), BinderInfo::Default, &md_nat, &nat);
    let ty = Expr::mk_pi(&Name::str("a"), BinderInfo::Default, &md_nat, &inner);
    assert_eq!(ty.hash(), 4163592787);
    assert_eq!(ty.approx_depth(), 3);
}

// CONST Nat.mul kind=def type_hash=4163592787 (same as Nat.add — same structure)
#[test]
fn test_nat_mul_type() {
    let nat = Expr::mk_const(&Name::str("Nat"), &[]);
    let md_nat = Expr::mk_mdata(&nat);
    let inner = Expr::mk_pi(&Name::str("a"), BinderInfo::Default, &md_nat, &nat);
    let ty = Expr::mk_pi(&Name::str("a"), BinderInfo::Default, &md_nat, &inner);
    assert_eq!(ty.hash(), 4163592787);
}

// CONST Eq kind=induct lp=1 type_hash=3970007004 type_depth=3
// Eq.{u} : {α : Sort u} → α → α → Prop
// = Pi("α", Sort(param u), Implicit, Pi("a", #0, Pi("b", #1, Sort 0)))
#[test]
fn test_eq_type() {
    let u = Level::mk_param(&Name::str("u_1"));  // Lean uses u_1 for Eq
    let sort_u = Expr::mk_sort(&u);
    let prop = Expr::mk_sort(&Level::zero());
    // {α : Sort u_1} → α → α → Prop
    // Pi(α, Sort u_1, Pi(a, #0, Pi(b, #1, Sort 0)), Implicit)
    let innermost = Expr::mk_pi(&Name::str("a_1"), BinderInfo::Default,
        &Expr::mk_bvar(1), &prop);
    let middle = Expr::mk_pi(&Name::str("a"), BinderInfo::Default,
        &Expr::mk_bvar(0), &innermost);
    let ty = Expr::mk_pi(&Name::str("α"), BinderInfo::Implicit,
        &sort_u, &middle);
    assert_eq!(ty.hash(), 3970007004, "Eq type hash");
    assert_eq!(ty.approx_depth(), 3);
    assert!(ty.has_univ_param());
}

// CONST Prod kind=induct lp=2 type_hash=3173088088 type_depth=2
// Prod.{u,v} : Type u → Type v → Type (max u v)
// Level params: the actual Lean names may differ; verify via Sort level hashes.
// From DumpTypes: Sort h=2271366212 (succ param u), Sort h=540585106 (succ param v),
//                 Sort h=3326628809 (succ max(u,v))
#[test]
fn test_prod_type() {
    // First verify the level hashes match
    let u = Level::mk_param(&Name::str("u"));
    let v = Level::mk_param(&Name::str("v"));
    assert_eq!(Level::mk_succ(&u).hash(), 2271366212, "succ(param u)");
    assert_eq!(Level::mk_succ(&v).hash(), 540585106, "succ(param v)");

    let type_u = Expr::mk_sort(&Level::mk_succ(&u));
    let type_v = Expr::mk_sort(&Level::mk_succ(&v));
    // Lean stores: max(succ u, succ v), NOT succ(max(u, v))
    // These are semantically equivalent but structurally different.
    let su = Level::mk_succ(&u);
    let sv = Level::mk_succ(&v);
    let type_max = Expr::mk_sort(&Level::mk_max_core(&su, &sv));
    let inner = Expr::mk_pi(&Name::str("β"), BinderInfo::Default, &type_v, &type_max);
    let ty = Expr::mk_pi(&Name::str("α"), BinderInfo::Default, &type_u, &inner);
    assert_eq!(ty.hash(), 3173088088, "Prod type hash");
    assert_eq!(ty.approx_depth(), 2);
}

// Verify some depth=0 constants' type hashes to cross-check
// CONST Quot kind=quot lp=1 type_hash=4084769648 type_depth=4
// Quot.{u} : {α : Sort u} → (α → α → Prop) → Sort u
#[test]
fn test_quot_type() {
    let u = Level::mk_param(&Name::str("u"));
    let sort_u = Expr::mk_sort(&u);
    let prop = Expr::mk_sort(&Level::zero());
    // α → α → Prop
    let rel_body = Expr::mk_pi(&Name::str("a✝"), BinderInfo::Default,
        &Expr::mk_bvar(1), &prop);
    let rel_type = Expr::mk_pi(&Name::str("a✝"), BinderInfo::Default,
        &Expr::mk_bvar(0), &rel_body);
    // {α : Sort u} → (α → α → Prop) → Sort u
    let inner = Expr::mk_pi(&Name::str("r"), BinderInfo::Default,
        &rel_type, &sort_u);
    let ty = Expr::mk_pi(&Name::str("α"), BinderInfo::Implicit,
        &sort_u, &inner);
    assert_eq!(ty.hash(), 4084769648, "Quot type hash");
    assert_eq!(ty.approx_depth(), 4);
}
