//! Verify name hashes for ALL 53,804 constants in Init against the real
//! Lean 4.25.2 C++ kernel.
//!
//! Source: /r/tmp/lean4/all_hashes.txt generated by DumpAllHashes.lean

use lean4_kernel::name::Name;

const HASH_FILE: &str = "/r/tmp/lean4/all_hashes.txt";

/// Parse a Lean hierarchical name from its escaped string representation.
/// Handles «guillemets» for non-standard identifiers.
/// Examples: "Nat.succ", "«term_×'__1»", "Lean.«term_<|>_»"
fn parse_lean_name(s: &str) -> Name {
    let mut name = Name::anonymous();
    let chars: Vec<char> = s.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        // Skip leading dot (separator between components)
        if chars[i] == '.' && i > 0 {
            i += 1;
            if i >= chars.len() { break; }
        }
        if chars[i] == '«' {
            // Guillemet-escaped component: find closing »
            i += 1; // skip «
            let start = i;
            while i < chars.len() && chars[i] != '»' {
                i += 1;
            }
            let component: String = chars[start..i].iter().collect();
            name = Name::mk_string(&name, &component);
            if i < chars.len() { i += 1; } // skip »
        } else {
            // Regular component: read until '.' or end
            let start = i;
            while i < chars.len() && chars[i] != '.' {
                i += 1;
            }
            let component: String = chars[start..i].iter().collect();
            if let Ok(n) = component.parse::<u64>() {
                name = Name::mk_numeral(&name, n);
            } else {
                name = Name::mk_string(&name, &component);
            }
        }
    }
    name
}

#[test]
fn test_all_init_name_hashes() {
    let content = match std::fs::read_to_string(HASH_FILE) {
        Ok(c) => c,
        Err(_) => {
            eprintln!("SKIP: {} not found (run DumpAllHashes.lean first)", HASH_FILE);
            return;
        }
    };

    let mut total = 0u64;
    let mut matched = 0u64;
    let mut mismatched = 0u64;
    let mut first_failures: Vec<String> = Vec::new();

    for line in content.lines() {
        if line.starts_with("TOTAL") || line.starts_with("DumpAll") || line.starts_with("Note:") || line.is_empty() {
            continue;
        }
        // Format: "Name.With.Dots name_hash type_hash"
        // We need to split from the right since name can contain spaces? No — Lean names don't.
        // But the name itself is everything before the second-to-last token.
        let parts: Vec<&str> = line.rsplitn(3, ' ').collect();
        if parts.len() < 3 {
            continue;
        }
        let _type_hash = parts[0]; // we can't verify this without constructing the type
        let name_hash_str = parts[1];
        let name_str = parts[2];

        let expected_hash: u64 = match name_hash_str.parse() {
            Ok(h) => h,
            Err(_) => continue,
        };

        let name = parse_lean_name(name_str);
        total += 1;

        if name.hash() == expected_hash {
            matched += 1;
        } else {
            mismatched += 1;
            if first_failures.len() < 20 {
                first_failures.push(format!(
                    "  {} : got {} expected {}",
                    name_str, name.hash(), expected_hash
                ));
            }
        }
    }

    eprintln!("Init name hash verification:");
    eprintln!("  Total:     {}", total);
    eprintln!("  Matched:   {} ({:.1}%)", matched, 100.0 * matched as f64 / total as f64);
    eprintln!("  Mismatched: {}", mismatched);

    if !first_failures.is_empty() {
        eprintln!("First mismatches:");
        for f in &first_failures {
            eprintln!("{}", f);
        }
    }

    // We expect 100% match on name hashes
    assert_eq!(mismatched, 0,
        "{} name hashes mismatched out of {} (first: {})",
        mismatched, total,
        first_failures.first().map(|s| s.as_str()).unwrap_or("?"));
}
